### ISSUE TITLE
Xcode 8 latest swift 3 Support ?

### ISSUE THREAD

**Issue by ismaelgobernado** [DragonCherry/HFSwipeView#1]

**Comment by DragonCherry** [comment]
I've got involved in a busy project now. But I'll update it in the near future.

**Comment by DragonCherry** [comment]
HFSwipeView supports Swift 3 at develop branch now, and I will release it with new version after UI test.

**Comment by siberian1967** [comment]
Testing here as well, tx!

**Comment by DragonCherry** [comment]
Refer to first release version 1.1.0 for Swift 3

**Comment by DragonCherry** [comment]
released 1.1.1 with minor bug fixes
