### ISSUE TITLE
Support For RTL and LTR semantic

### ISSUE THREAD

**Issue by SyedGhaus** [DragonCherry/HFSwipeView#5]
Hi,
Will there be support for the RTL as currently it is misbehaving if in arabic.

**Comment by DragonCherry** [comment]
Would you please tell me how to reproduce the misbehavior that you met?

**Comment by SyedGhaus** [comment]
Just add the localisation of arabic in the example of urs and try it on setting the simulator language to arabic u can see that easily

Regards,

Syed Ghaus,
Senior IOS Developer

Mob       +971 55 673 5731
Email:     Syed.Ghaus@intigral.net<mailto:Syed.Ghaus@intigral.net>

On 11-Feb-2017, at 11:38 AM, DragonCherry <notifications@github.com<mailto:notifications@github.com>> wrote:


Would you please tell me how to reproduce the misbehavior that you met?

**Comment by DragonCherry** [comment]
OK, I'll check it out during this week.

**Comment by DragonCherry** [comment]
I'm sorry but it will take more time to start check this out due to my personal reasons.

**Comment by DragonCherry** [comment]
Hello, I'm trying to support RTL semantics on new branch named "support-RTL" and you can see how's it going by monitoring it. I'm not sure how much time it will take but I'll finish it on some day in the future :)

**Comment by SyedGhaus** [comment]
Thank you so much man. :) Definitely will be looking into it.

Regards,

Syed Ghaus,
Senior IOS Developer

Mob       +971 55 673 5731
Email:     Syed.Ghaus@intigral.net

**Comment by DragonCherry** [comment]
HFSwipeView supports RTL semantics in new release(1.1.4). Notify me if you find any bugs in there.
