### ISSUE TITLE
Crash app if the self.count = 0, please fix it on swift 3

### ISSUE THREAD

**Issue by haphan2014** [DragonCherry/HFSwipeView#6]
public func autoSlideCallback(_ timer: Timer) {
        DispatchQueue.main.async {
            self.movePage((self.currentPage + 1) % self.count, animated: true)
        }
    }

**Comment by DragonCherry** [comment]
Thank you for reporting this bug, I'll definitely fix this issue as soon as possible.

**Comment by DragonCherry** [comment]
This bug you reported has been fixed in release version 1.1.5.
Please don't hesitate to tell me if any wrong behaviour with it.
